[package]
name = "searchlite-node"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Node.js native addon for searchlite"

[features]
default = []
vectors = ["searchlite-core/vectors"]
zstd = ["searchlite-core/zstd"]

[dependencies]
searchlite-core = { path = "../searchlite-core", features = ["write-key"] }
napi = { version = "3", features = ["serde-json", "napi9"] }
napi-derive = "3"
serde_json = { workspace = true }
anyhow = { workspace = true }

[build-dependencies]
napi-build = "2"

[lib]
crate-type = ["cdylib"]
